version: 2.1

workflows:
    build:
      jobs:
        - test

jobs:
  test:
    docker:
      - image: cimg/ruby:3.1.2
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: bundle install
      - run:
          name: Run tests
          command: rspec
      - run:
          name: Run rubocop
          command: rubocop
      - run:
          name: Run fasterer
          command: fasterer