version: 2.1

executors:
  default:
    working_directory: ~/repo
    description: The official Docker image
    docker:
      - image: cimg/ruby.3.1.2
        environment:
          RAILS_ENV: test

caches:
  - &bundle_cache_v1 v2-repo-{{ checksum "Gemfile.lock }}
  - &bundle_cache v2-repo-

commands:
  defaults:
    steps:
      - checkout
      - run: bundle install
  run_specs:
    steps:
      - run:
          name: run specs
          command: rspec

jobs:
  run_specs:
    executor: default
    steps:
      - defaults
      - run_specs

workflows:
  build:
    jobs:
      - run_specs