version: 2.1

executors:
  default:
    working_directory: ~/repo
    description: Codebreaker gem project
    docker:
      -image: circleci/ruby:3.1.2
      environment:
        RAILS_ENV: test

  caches:
    - &bundle_cache_full v2-repo-{{ checksum "Gemfile.lock" }}
    - &bundle_cache v2-repo

  commands:
    defaults:
      steps:
        - checkout
        - run: bundle install
jobs:
  lintering:
    executor: default
      steps:
        -defaults

  workflows:
    version: 2.1
    build:
      jobs:
        - lintering